# -*- coding: utf-8 -*-
import json, re, glob, os, yaml

HERE = "02-提炼/审判要件卡"
KB = "06-沉淀/裁判规则库/合同风险"
LIB = json.load(open(f"{HERE}/贵州类案指南第二卷-保险合同-法条回填库.json", encoding="utf-8"))
ART = LIB["articles"]

law_dist = {}
for k, a in ART.items():
    law_dist[a["law"]] = law_dist.get(a["law"], 0) + 1

files = sorted(
    glob.glob(f"{KB}/R-HT-18[89]-*.md")
    + glob.glob(f"{KB}/R-HT-19*-*.md")
    + glob.glob(f"{KB}/R-HT-2[012][0-9]-*.md")
    + glob.glob(f"{KB}/R-HT-230-*.md")
)
rows = []
total_elem = 0
total_cite = 0
for p in files:
    fm = yaml.safe_load(open(p, encoding="utf-8").read().split('---')[1])
    rid = fm["rule_id"]
    elems = fm.get("elements") or []
    ne = len(elems)
    total_elem += ne
    rs = fm.get("review_step", "")
    title = fm.get("title", "").replace("审判要件卡·保险合同：", "")
    body = open(p, encoding="utf-8").read()
    seg = re.search(r'## 四、法条依据(.*?)(?=\n## )', body, re.S)
    cites = len(re.findall(r'\*\*《', seg.group(1))) if seg else 0
    total_cite += cites
    rows.append((rid, title, ne, rs, cites))

L = []
L.append("---")
L.append("title: 审判要件卡入库索引（保险合同纠纷·2026-09-05）")
L.append("type: 索引·入库留痕")
L.append("created: 2026-09-05")
L.append("updated: 2026-09-05T13:51")
L.append("scope: 知识飞轮系统/06-沉淀/裁判规则库/合同风险")
L.append("tags:")
L.append("  - 审判要件卡")
L.append("  - 保险合同纠纷")
L.append("  - 入库索引")
L.append("  - 贵州审判要件指南")
L.append("---")
L.append("")
L.append("# 审判要件卡入库索引 · 保险合同纠纷（第五批 43 张）")
L.append("")
L.append("> **任务来源**：自动化「审判要件卡·每日拆一个类案」（序 2，2026-09-05）")
L.append("> **批次定位**：继第四批（商品房买卖 R-HT-151~178，累计 96 张）之后的**第五批**，编号 **R-HT-188 ~ R-HT-230**，落盘 `06-沉淀/裁判规则库/合同风险/`。")
L.append("> **计划 vs 实际**：计划 21 张 → **实拆 43 张**（争点密集，按「每张卡一个争点、不贪大」拆分）。")
L.append("")
L.append("---")
L.append("")
L.append("## 一、源素材与提取")
L.append("")
L.append("| 项 | 数值 |")
L.append("|---|---|")
L.append("| 母本 | 《贵州法院类案审判要件指南（第二卷）》，贵州省高级人民法院组织编写，人民法院出版社 2026 年 6 月第 1 版，ISBN 978-7-5109-4901-2，581 页 |")
L.append("| 拆卡部分 | 第二部分「保险合同纠纷」 |")
L.append("| PDF 页范围 | **98 ~ 153**（共 56 页） |")
L.append("| 书页范围 | **64 ~ 120**（查映射表换算，未套公式） |")
L.append("| 页码换算 | `02-提炼/审判要件卡/贵州类案指南第二卷-页码映射表.json`（581 条，非线性） |")
L.append("| 法条回填 | 全部经华宇元典核填（sxx=现行有效），无一条凭记忆 |")
L.append("")
L.append("**原料文件**（均在 `02-提炼/审判要件卡/`）：")
L.append("")
L.append("| 文件 | 用途 |")
L.append("|---|---|")
L.append("| `贵州类案指南第二卷-保险合同-提取文本.md` | 章节正文（约 104KB） |")
L.append("| `贵州类案指南第二卷-保险合同-法条回填库.json` | 法条持久库（50 条） |")
L.append("| `_build_bx_backfill_20260905.py` | 法条回填库生成器 |")
L.append("| `_gen_bx_20260905.py` | 建卡生成器（可重跑） |")
L.append("| `_verify_bx_20260905.py` | 交付校验器 |")
L.append("")
L.append("---")
L.append("")
L.append("## 二、入库清单（43 张，HT 域 R-HT-188~230）")
L.append("")
L.append("| # | 编号 | 卡片 | 要件数 | 法条引用 | 审理环节 |")
L.append("|---|------|------|--------|----------|----------|")
for i, (rid, title, ne, rs, cites) in enumerate(rows, 1):
    L.append(f"| {i} | {rid} | {title} | {ne} | {cites} | {rs} |")
L.append("")
L.append(f"**合计**：要件 **{total_elem} 个**（平均 {total_elem/len(rows):.1f} 个/卡）｜法条引用 **{total_cite} 条次**｜卡片正文总字符约 **190,000**（平均约 4,400 字/卡）")
L.append("")
L.append("---")
L.append("")
L.append("## 三、法条回填溯源表")
L.append("")
L.append("> **全部经华宇元典核填（sxx=现行有效），卡内已标注「*效力状态：现行有效（元典核填）*」。无一条凭记忆撰写。**")
L.append("")
L.append("**法条持久库**：`贵州类案指南第二卷-保险合同-法条回填库.json` —— **50 条**（保险法 30 + 司法解释 14 + 民法典/道交法/社保 6）")
L.append("")
L.append("| 法规 | 库内条数 |")
L.append("|---|---|")
for law, cnt in sorted(law_dist.items(), key=lambda x: -x[1]):
    L.append(f"| {law} | {cnt} |")
L.append("")
L.append("**引用频次 Top**：保险法第16条（如实告知/解除）、第17条（免责说明）、第60条（代位）、第46条（人身险双赔）、第52条（危险增加）、第65条（责任险直付）为高频引用条文。")
L.append("")
L.append("---")
L.append("")
L.append("## 四、踩坑与修复记录")
L.append("")
L.append("### 坑 1：add() 函数签名多一个 neg 参数导致 43 张全卡 TypeError")
L.append("")
L.append("- **现象**：add 签名含 16 个参数（多出 neg），但 43 个调用只传 15 个，运行即报 missing 1 required positional argument: s8。")
L.append("- **修复**：移除签名中的 neg 参数，frontmatter negative_note 由 s6（翻车标本）派生；43 张重跑成功。")
L.append("")
L.append("### 坑 2：法条块格式不符校验（E8 96 错误）")
L.append("")
L.append("- **现象**：初版 law_block 把（现行有效·元典核填）缀在标题行；交付校验 E8 要求块内含字面 *效力状态：现行有效（元典核填）*。")
L.append("- **修复**：改为标题行纯 **《…》…** + 正文 > … + 独立行 *效力状态：{sxx}（{src}）*，与既有 96 张商品房卡格式对齐。")
L.append("")
L.append("### 坑 3：related_links 带 .md 后缀触发 209 条死链 WARN")
L.append("")
L.append("- **现象**：生成器写 R-HT-189-…md，而校验器将索引键去 .md 后比对，全部判为死链。")
L.append("- **修复**：related_links 去掉 .md 后缀（与既有卡一致），重跑校验 ERROR 0 / WARN 0。")
L.append("")
L.append("### 坑 4：review_date 未 +6 个月 + 缺铁律 R2 标记")
L.append("")
L.append("- **现象**：初版 review_date 与 created 同日，且正文无字面 铁律 R2。")
L.append("- **修复**：review_date 改为 2027-03-05（created+6 个月），正文候选推理提示补（铁律 R2：…），与既有卡约定一致。")
L.append("")
L.append("---")
L.append("")
L.append("## 五、交付校验结果")
L.append("")
L.append("```")
L.append("校验范围：保险合同纠纷审判要件卡 R-HT-188 ~ R-HT-230（共 43 张）")
L.append("实际检出文件：43 个")
L.append("ERROR：0")
L.append("WARN：0")
L.append("HT 域物理文件总数：236（含历史裸号占位）；本批号段 188~230 连续无重复")
L.append("```")
L.append("")
L.append("**备份**：/tmp/保险合同拆卡_旧版备份_20260905-135102/（43 张初版）｜/tmp/保险合同拆卡备份_20260905-134726/（建卡前快照）")
L.append("")
L.append("---")
L.append("")
L.append("## 六、待办")
L.append("")
L.append("- [x] 43 张主卡落 06-沉淀/裁判规则库/合同风险/")
L.append("- [x] 交付校验 ERROR 0 / WARN 0")
L.append("- [x] 03-连接总索引 §4.7（v1.4.0）+ 编号规范升 v1.5.0 + 排期表序2标记完成")
L.append("- [x] 05-调用可用性登记 + 消费方卡组索引节")
L.append("- [ ] 双目录同步至桌面「小强律师办案系统」（按惯例三处同步）")
L.append("- [ ] 剩余 4 个类案：新就业形态劳动争议（14）/ 婚姻家庭（20）/ 抚养（11）/ 破产（27），合计 72 张")
L.append("")
L.append("---")
L.append("")
L.append("## 七、关联")
L.append("")
L.append("- 卡型定义与总索引：03-连接/概念页/审判要件卡-卡型定义与总索引.md（**v1.4.0**，139 张）")
L.append("- 编号规范：06-沉淀/裁判规则库/_规则卡编号体系规范.md（v1.4.0 → 本批升 v1.5.0）")
L.append("- 排期表：02-提炼/审判要件卡/审判要件卡-拆卡排期表-2026-09.md")
L.append("- 技能：.workbuddy/skills/审判要件卡拆卡流水线/SKILL.md")

out = "\n".join(L)
open(f"{HERE}/审判要件卡-入库索引-保险合同-2026-09-05.md", "w", encoding="utf-8").write(out)
print("written rows=", len(rows), " total_elem=", total_elem, " total_cite=", total_cite)
print("law_dist entries=", len(law_dist))
