# -*- coding: utf-8 -*-
"""破产案件批·六层挂载 之二：02-提炼入库索引 + 05-调用可用性登记"""
import importlib.util, os, re, json

BASE = "/Users/chenyouqiang/Documents/LawKB/知识飞轮系统"
D = f"{BASE}/02-提炼/审判要件卡"
LAWJ = f"{D}/贵州类案指南第二卷-破产案件-法条回填库.json"
LAWS = json.load(open(LAWJ, encoding="utf-8"))

def load(f):
    spec = importlib.util.spec_from_file_location("m_" + f[:-3], f"{D}/{f}")
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
    return m.CARDS

ALL = []
for f in ["_gs_cards1_20260908.py", "_gs_cards2_20260908.py",
          "_gs_cards3_20260908.py", "_gs_cards4_20260908.py"]:
    ALL += load(f)

n_el = sum(len(c["el"]) for c in ALL)
n_law_ref = sum(len(c["laws"]) for c in ALL)
law_keys = []
for c in ALL:
    for k in c["laws"]:
        if k not in law_keys: law_keys.append(k)
n_full = sum(1 for k in law_keys if LAWS.get(k, {}).get("source") == "北大法宝核填")
n_pend = len(law_keys) - n_full

# ---------- 02-提炼 入库索引 ----------
p1 = f"{D}/审判要件卡-入库索引-破产案件-2026-09-08.md"
L = []
L.append("---")
L.append("title: 审判要件卡入库索引·破产案件（2026-09-08）")
L.append("type: 提炼·入库索引")
L.append("created: 2026-09-08")
L.append("batch: 第九批")
L.append("domain: GS（公司治理）")
L.append("scope: 知识飞轮系统/06-沉淀/裁判规则库/公司法")
L.append("tags:")
L.append("  - 审判要件卡")
L.append("  - 破产案件")
L.append("  - 入库索引")
L.append("---")
L.append("")
L.append("# 审判要件卡入库索引 · 破产案件（2026-09-08 · 第九批 90 张）")
L.append("")
L.append("## 一、批次概览")
L.append("")
L.append("| 项 | 值 |")
L.append("|---|---|")
L.append("| 母本 | 《贵州法院类案审判要件指南（第二卷）》第九部分「破产案件审判要件指南」 |")
L.append("| 母本位置 | PDF页 448-513 / 书页 418-485 |")
L.append("| 计划张数 | 27 |")
L.append("| 实拆张数 | **90** |")
L.append("| 号段 | **R-GS-005 ~ R-GS-094** |")
L.append("| 落盘目录 | `06-沉淀/裁判规则库/公司法/` |")
L.append("| 取号依据 | GS 域物理 max 实测 004 → 起始 005，一次性连续取满 |")
L.append("| 要件总数 | %d 个（均 %.1f/卡） |" % (n_el, n_el / len(ALL)))
L.append("| 法条引用 | %d 条次（去重后 %d 条） |" % (n_law_ref, len(law_keys)))
L.append("| 交付校验 | **ERROR 0 / WARN 0** |")
L.append("| 死链自检 | **0** |")
L.append("")
L.append("## 二、页码换算（铁律：查映射表，不套线性公式）")
L.append("")
L.append("映射表：`02-提炼/审判要件卡/贵州类案指南第二卷-页码映射表.json`（581 条，非线性）")
L.append("")
L.append("| 锚点 | PDF页 | 书页 | 线性公式（PDF−35）结果 | 偏差 |")
L.append("|---|---|---|---|---|")
L.append("| 部分标题页 | 448 | 418 | 413 | +5 |")
L.append("| 正文起始 | 450 | 421 | 415 | +6 |")
L.append("| 章节中段 | 480 | 452 | 445 | +7 |")
L.append("| 章节末页 | 513 | 485 | 478 | +7 |")
L.append("")
L.append("> 线性公式在本段偏差 +5~+7，**再次验证坑 4「严禁套线性公式」**。全批 90 张卡 source 字段均经映射表换算。")
L.append("")
L.append("## 三、法条溯源")
L.append("")
L.append("| 项 | 值 |")
L.append("|---|---|")
L.append("| 法条持久库 | `02-提炼/审判要件卡/贵州类案指南第二卷-破产案件-法条回填库.json` |")
L.append("| 已核填（北大法宝 get_article 真调用） | **%d 条** |" % n_full)
L.append("| 待回源（指南引述·据实标注） | %d 条 |" % n_pend)
L.append("| 合计 | %d 条 |" % len(law_keys))
L.append("| 回填铁律 | 正文一律来自权威源核填，**零凭记忆**；未核填的一律标「指南引述·待回源核填」，不虚标「元典核填」 |")
L.append("")
L.append("### 3.1 法宝核填条文清单（效力状态：现行有效）")
L.append("")
L.append("| 法规 | 条号 |")
L.append("|---|---|")
seen_law = {}
for k in law_keys:
    v = LAWS.get(k, {})
    if v.get("source") == "北大法宝核填":
        seen_law.setdefault(v["law"], []).append(v["article"])
for law, arts in seen_law.items():
    L.append(f"| {law} | {('、'.join('§' + a for a in arts))} |")
L.append("")
L.append("### 3.2 待回源清单（指南引述，未取得条文正文）")
L.append("")
pend = [LAWS[k] for k in law_keys if LAWS.get(k, {}).get("source") != "北大法宝核填"]
for v in pend:
    L.append(f"- {v['law']}：{v['text'][:60]}")
L.append("")
L.append("> 上述条文仅作索引提示，**不得作为文书直接引用正文**；引用前须经国家法律法规数据库（flk.npc.gov.cn）或最高法官网二次核填。")
L.append("")
L.append("## 四、卡片清单（90 张）")
L.append("")
L.append("| 号 | 卡名 | 审理环节 | 法条引用 |")
L.append("|---|---|---|---|")
for c in ALL:
    L.append(f"| R-GS-{c['no']} | {c['title']} | {c['step']} | {len(c['laws'])} |")
L.append("")
L.append("## 五、数字留痕")
L.append("")
L.append("- 建卡生成器：`_gs_cards1~4_20260908.py`（数据）+ `_gen_gs_20260908.py`（渲染）")
L.append("- 法条库建造：`_build_gs_backfill_20260908.py`")
L.append("- 交付校验器：`_verify_gs_20260908.py`（ERROR 0 / WARN 0）")
L.append("- 挂载脚本：`_mount1_gs_20260908.py`（总索引）、`_mount2_gs_20260908.py`（本文件 + 可用性登记）")
L.append("- 备份目录：`/tmp/破产案件拆卡备份_20260908-1136/`")
L.append("")
open(p1, "w", encoding="utf-8").write("\n".join(L))
print(f"入库索引: {p1} ({os.path.getsize(p1)} bytes)")

# ---------- 05-调用 可用性登记 ----------
p2dir = f"{BASE}/05-调用/模拟法庭调用记录"
os.makedirs(p2dir, exist_ok=True)
p2 = f"{p2dir}/审判要件卡-卡组可用性登记-破产案件-2026-09-08.md"
M = []
M.append("---")
M.append("title: 审判要件卡卡组可用性登记·破产案件（2026-09-08）")
M.append("type: 调用·可用性登记")
M.append("created: 2026-09-08")
M.append("batch: 第九批")
M.append("domain: GS（公司治理）")
M.append("consumer: 模拟法庭 judge_reviewer")
M.append("tags:")
M.append("  - 审判要件卡")
M.append("  - 卡组可用性")
M.append("  - 破产案件")
M.append("---")
M.append("")
M.append("# 卡组可用性登记 · 破产案件（R-GS-005~094，90 张）")
M.append("")
M.append("## 一、卡组状态")
M.append("")
M.append("| 项 | 值 |")
M.append("|---|---|")
M.append("| 卡组规模 | 90 张 |")
M.append("| 号段 | R-GS-005 ~ R-GS-094（连续，无空洞） |")
M.append("| 落盘 | `06-沉淀/裁判规则库/公司法/` |")
M.append("| 交付校验 | ERROR 0 / WARN 0 ✅ |")
M.append("| 死链自检 | 0 ✅ |")
M.append("| 法条标注 | 北大法宝核填 %d 条 + 待回源 %d 条（据实标注） |" % (n_full, n_pend))
M.append("| 可用性 | ✅ 可消费（候选推理，非自动裁判） |")
M.append("")
M.append("## 二、法官心智四步调用映射")
M.append("")
M.append("| 步骤 | 消费字段 | 本卡组支撑 |")
M.append("|---|---|---|")
M.append("| ① 定位审理环节 | `review_step` | 覆盖立案审查、管理人指定、财产甄别、债权审查、清偿顺位、衍生诉讼、重整、和解、清算全环节 |")
M.append("| ② 逐项涵摄 | `elements` | %d 个要件，均 %.1f/卡 |" % (n_el, n_el / len(ALL)))
M.append("| ③ 举证校验 | `burden_of_proof` | 90 张全覆盖 |")
M.append("| ④ 裁判预判 + 但书 | `ruling.support` / `ruling.reject` / `negative_note` | 90 张全覆盖 |")
M.append("")
M.append("## 三、⚠️ 消费方使用警示（本批最高价值）")
M.append("")
M.append("1. **🔴 共益债务边界（R-GS-048~053）**：**重整计划执行期间 ≠ 重整期间**。该期间投资人已接管经营、管理人仅监督，新发生债务**不属于**§42 列举的共益债务（本质是投资人对全体债权人违约）。与「重整期间继续营业债务属§42④共益债务」是完全不同的两段规则，混用将直接改变清偿顺位。")
M.append("2. **🔴 破产受理后一律禁止个别清偿（R-GS-037）**：即使已有生效判决判令股东向债权人承担补充赔偿责任，破产受理后股东仍须向**债务人**补缴（§16、§35），不得个别清偿。")
M.append("3. **🔴 实质合并以单个破产程序为原则（R-GS-014~017）**：须「人格高度混同」＋「分别具备破产原因」＋「听证」三重门槛，非因关联关系即合并。")
M.append("4. **和解无强制批准（R-GS-066）**：和解协议草案未获债权人会议通过的，**不得**参照重整强制批准规则，应裁定终止并宣告破产。")
M.append("5. **和解协议与重整计划均非执行依据／不及于保证人（R-GS-058、R-GS-067、R-GS-068）**：裁定认可的和解协议不能申请强制执行；免责效力不及于保证人和其他连带债务人。")
M.append("6. **刑事罚金劣后（R-GS-021）**：刑事罚金属惩罚性债权，劣后于普通破产债权，且仅在§113清偿后有剩余时才可清偿。")
M.append("7. **滞纳金封顶（R-GS-041、R-GS-064）**：依行政强制法§45②，加收滞纳金不得超出税款本金，超出部分不认定为普通债权。")
M.append("8. **15日异议期非除斥期间（R-GS-083）**：逾期不消灭诉权，法院不得拒绝受理。")
M.append("")
M.append("## 四、跨案可复用性评估")
M.append("")
M.append("| 在手案件 | 可复用卡 | 复用点 |")
M.append("|---|---|---|")
M.append("| 吊顶案 6658 号 | R-GS-089、R-GS-073、R-GS-087 | 房开破产购房人权利顺位（若涉房开主体破产）、实际施工人突破相对性与个别清偿 |")
M.append("| 雅菲案 6660 号 | R-GS-008、R-GS-010 | 破产原因认定、撤回申请与驳回的处理（若被告涉破产） |")
M.append("| 王德明担保案执行异议 | R-GS-058、R-GS-042~044 | 保证人不得以重整计划对抗债权人、保证债权申报 |")
M.append("| 韩杰医疗事故案 | R-GS-069 | 人身损害赔偿债权优先于财产债权（若涉机构破产） |")
M.append("| 厚德基金会法律服务 | R-GS-005、R-GS-061 | 三类破产程序分野、非法人组织不得重整 |")
M.append("")
M.append("## 五、调用纪律")
M.append("")
M.append("- **铁律 R2**：本卡组输出为**候选推理**，须标注【候选·待人工确认】，不得作为自动裁判结论。")
M.append("- 跨省援引须核当地口径（geo_scope: 贵州省）。")
M.append("- 待回源条文（%d 条）引用前须二次核填，不得直接引用正文。" % n_pend)
M.append("")
open(p2, "w", encoding="utf-8").write("\n".join(M))
print(f"可用性登记: {p2} ({os.path.getsize(p2)} bytes)")
print(f"要件 {n_el} 个 / 法条引用 {n_law_ref} 条次 / 去重 {len(law_keys)} 条（核填 {n_full} + 待回源 {n_pend}）")
