# -*- coding: utf-8 -*-
"""第七批 婚姻家庭 六层挂载（02-提炼入库索引 / 05-调用可用性登记）"""
import os, re, io, sys

ROOT = "/Users/chenyouqiang/Documents/LawKB/知识飞轮系统"
CARD_DIR = os.path.join(ROOT, "06-沉淀/裁判规则库/婚姻家庭")
TODAY = "2026-09-07"

# ---- 实地读卡 ----
cards = []
for fn in sorted(os.listdir(CARD_DIR)):
    m = re.match(r'^(R-HY-(\d{3}))-(.+)\.md$', fn)
    if not m:
        continue
    rid, num, short = m.group(1), int(m.group(2)), m.group(3)
    txt = io.open(os.path.join(CARD_DIR, fn), encoding='utf-8').read()
    fm = txt.split('---')[1] if txt.startswith('---') else ''
    def g(k, default=''):
        mm = re.search(r'(?m)^%s:\s*(.*)$' % re.escape(k), fm)
        return mm.group(1).strip() if mm else default
    title = g('title') or short
    step = g('review_step')
    # 法条条次：正文「**《X》第N条**」计数
    lawblocks = re.findall(r'\*\*《([^》]+)》第([零一二三四五六七八九十百千]+)条\*\*', txt)
    cards.append(dict(rid=rid, num=num, short=short, title=title, step=step,
                      nlaw=len(lawblocks), fn=fn))
cards.sort(key=lambda c: c['num'])
print("[实地] HY 域卡片 %d 张，号段 %s ~ %s" % (len(cards), cards[0]['rid'], cards[-1]['rid']))
TOTAL_LAW = sum(c['nlaw'] for c in cards)
print("[实地] 法条块合计 %d 条次" % TOTAL_LAW)

GROUPS = [
    ("A", "审理原则与立案审查", 4, 6, "审理思路·一、二：四项审理原则、管辖九类、不予受理九类", "程序战：管辖异议 / 起诉条件"),
    ("B", "身份关系类纠纷审查", 7, 16, "审理思路·三：离婚主体、准予离婚法定情形、无效与可撤销婚姻、调解程序", "身份关系：离或不离 / 婚效力"),
    ("C", "婚约财产与彩礼", 17, 21, "审理思路·四：婚约财产主体、彩礼范围、借婚姻索取财物、返还比例裁量、生活困难认定", "彩礼返还：范围界定与比例裁量"),
    ("D", "财产归属与债务认定", 22, 27, "审理思路·五：个人财产、共同财产申报、不动产出资登记、个人债务、共同债务", "财产定性：归谁 / 谁还"),
    ("E", "财产分割与擅自处分", 28, 34, "审理思路·六：婚内分割、房屋分割三路径、父母出资、特殊房屋、股权份额、同居分割、赠与第三者返还", "分割方案：怎么分 / 擅自处分追回"),
    ("F", "与婚姻有关的财产协议", 35, 39, "审理思路·七：婚内协议与忠诚协议、约定对外效力、离婚协议生效、约定不明与赠与子女、反悔撤销与违约金", "协议效力：能不能反悔"),
    ("G", "损害赔偿", 40, 42, "审理思路·八：请求主体与管辖、欺诈性抚养、程序规则", "离婚损害赔偿：赔不赔 / 怎么赔"),
    ("H", "扶养赡养与人身安全保护令", 43, 47, "审理思路·九、十：夫妻扶养、赡养义务主体与减免、保护令主体与执行", "扶养赡养费 / 家暴保护令"),
    ("I", "附录案例", 48, 55, "第四章 附录十案例（本批收录其一、二、四、五、七、八、九、十）", "类比推理锚点"),
]

def rows_for(a, b):
    return [c for c in cards if a <= c['num'] <= b]

OUT = []
OUT.append("---")
OUT.append("type: 审判要件卡·入库索引")
OUT.append("batch: 第七批")
OUT.append("domain: HY（婚姻家事）")
OUT.append("range: R-HY-004~055")
OUT.append("count: 52")
OUT.append("program_type: 民事（婚姻家庭纠纷）")
OUT.append("source_pdf: 《贵州法院类案审判要件指南（第二卷）》第五部分（PDF页254-306 / 书页222-275）")
OUT.append("landing: 知识飞轮系统/06-沉淀/裁判规则库/婚姻家庭/")
OUT.append("lawlib: 02-提炼/审判要件卡/贵州类案指南第二卷-婚姻家庭-法条回填库.json（9 部 / 165 条）")
OUT.append("verify: ERROR 0 / WARN 0")
OUT.append("created: %sT09:50" % TODAY)
OUT.append("updated: %sT09:50" % TODAY)
OUT.append("tags:")
OUT.append("  - 审判要件卡")
OUT.append("  - 入库索引")
OUT.append("  - 婚姻家庭")
OUT.append("  - 离婚财产分割")
OUT.append("  - 彩礼返还")
OUT.append("  - 贵州审判要件指南")
OUT.append("---")
OUT.append("")
OUT.append("# 审判要件卡 · 入库索引（第七批 · 婚姻家庭纠纷 52 张）")
OUT.append("")
OUT.append("> **落盘**：`06-沉淀/裁判规则库/婚姻家庭/`，号段 **R-HY-004~055**（HY 域物理文件总数 55，本批 52 张）。")
OUT.append("> **母本**：《贵州法院类案审判要件指南（第二卷）》**第五部分「婚姻家庭纠纷案件审判要件指南」**（PDF页254-306 / 书页222-275）。")
OUT.append("> **页码换算**：依 `02-提炼/审判要件卡/贵州类案指南第二卷-页码映射表.json`（581 条）逐页查表，**未用线性公式**（本书非线性，漂移 34→26）。")
OUT.append("> **取号铁律兑现**：拆卡当日实地取号，HY 物理 max=**003** → 起始 **004**，一次性连续取满 004~055，建卡过程未被并发摄入流水线抢占（建卡后实测仍为 055）。")
OUT.append("> **法条回填**：本会话华宇元典 / 北大法宝 MCP **未注册进本会话工具表**（已按「判定 MCP 不可用 6 步流程」逐项排查：`connector-states.json` 中 `pkulaw: enabled=True`、`yuandian-mcp: enabled=True`，真调用报「not found in the deferred tools index」）→ **降级走权威公开源核填**（court.gov.cn 公报 / gov.cn / 本地法律法规库），卡内标注一律写「**权威源核填**」，**不虚标「元典核填」**。法条库 **9 部 / 165 条**，卡内引用 **%d 条次**。" % TOTAL_LAW)
OUT.append("> **交付校验**：**ERROR 0 / WARN 0**（E0~E10 / W1~W4 全项通过）。")
OUT.append("")
OUT.append("## 一、批次概览")
OUT.append("")
OUT.append("| 项 | 值 |")
OUT.append("|---|---|")
OUT.append("| 批次 | 第七批（序 4 / 共 6） |")
OUT.append("| 类案 | 婚姻家庭纠纷 |")
OUT.append("| 计划张数 | 20（排期表） |")
OUT.append("| **实拆张数** | **52**（按「一卡一争点」，第四章其他问题 + 附录案例 + 抗辩审查均独立成卡） |")
OUT.append("| 号段 | R-HY-004~055 |")
OUT.append("| 法条库 | 9 部 / 165 条 |")
OUT.append("| 法条引用 | %d 条次 |" % TOTAL_LAW)
OUT.append("| related_links | 141 条（全数实测非死链） |")
OUT.append("| 落盘目录 | `06-沉淀/裁判规则库/婚姻家庭/` |")
OUT.append("")
OUT.append("> **计划 20 → 实拆 52 的口径说明**：排期表 20 张系按「章」估算。实际按「**一卡一争点**」拆分后，第五章财产分割（房屋三路径、父母出资、特殊房屋、股权份额、同居分割、赠与第三者）、第七章与婚姻有关协议（婚内协议、对外效力、生效条件、赠与子女、反悔撤销）与附录十案例各自独立成卡，故为 52 张。")
OUT.append("")
OUT.append("## 二、法条回填库构成（9 部 / 165 条）")
OUT.append("")
OUT.append("| 规范 | 条数 | 来源 |")
OUT.append("|------|------|------|")
OUT.append("| 中华人民共和国民法典 | 39 | 本地 `法律法规库/中华人民共和国民法典（全文）` |")
OUT.append("| 婚姻家庭编解释（一）（法释〔2020〕22号） | 64 | 权威公开源核填 |")
OUT.append("| 婚姻家庭编解释（二）（法释〔2025〕1号，2025-02-01 施行） | 20 | court.gov.cn/zixun/xiangqing/452771.html |")
OUT.append("| 中华人民共和国民事诉讼法（2023 修正） | 6 | 本地 `法律法规库`（`**第N条**` 加粗体，专用正则提取） |")
OUT.append("| 最高人民法院关于适用民事诉讼法的解释（2022 修正） | 8 | 权威公开源核填 |")
OUT.append("| 涉彩礼纠纷案件适用法律若干问题的规定（法释〔2024〕1号） | 7 | court.gov.cn |")
OUT.append("| 中华人民共和国老年人权益保障法 | 8 | gov.cn |")
OUT.append("| 中华人民共和国反家庭暴力法 | 12 | gov.cn |")
OUT.append("| 诉讼费用交纳办法 | 1 | gov.cn |")
OUT.append("")
OUT.append("> **提取越界防护**：首版正则字符类漏「零」，致「第一千零九十条」等条号越界吞并后续条文。已改 `[零一二三四五六七八九十百千]` 并取**首个匹配**，重建后**越界 0**。")
OUT.append("")
OUT.append("## 三、卡片清单（52 张 · 九组）")
OUT.append("")
for code, name, a, b, cov, use in GROUPS:
    rs = rows_for(a, b)
    OUT.append("### %s 组 · %s（R-HY-%03d~%03d，%d 张）" % (code, name, a, b, len(rs)))
    OUT.append("")
    OUT.append("> **覆盖**：%s　|　**用途**：%s" % (cov, use))
    OUT.append("")
    OUT.append("| 编号 | 卡名 | 审理环节 | 法条 |")
    OUT.append("|------|------|----------|------|")
    for c in rs:
        OUT.append("| [[%s]] | %s | %s | %d |" % (c['rid'] + '-' + c['short'], c['title'], c['step'] or '—', c['nlaw']))
    OUT.append("")
OUT.append("## 四、🔴 版本陷阱（本批最高价值登记）")
OUT.append("")
OUT.append("### 4.1 婚后父母出资购房分割口径已整体换版")
OUT.append("")
OUT.append("| 项 | 旧口径（已被取代） | **现行口径** |")
OUT.append("|---|---|---|")
OUT.append("| 规范 | 《婚姻家庭编解释（一）》第二十九条第二款 | **《婚姻家庭编解释（二）》第八条**（法释〔2025〕1号，**2025-02-01 施行**） |")
OUT.append("| 内容 | 婚后父母出资购房，无约定即**推定赠与夫妻双方** | 以**出资来源及比例为基础**，综合考量共同生活情况、孕育子女、离婚过错、对家庭贡献、房屋市场价格等因素**酌定**补偿 |")
OUT.append("| 后果 | 婚后父母出资**当然各半** | **不再当然各半**，须按出资比例 + 综合因素裁量 |")
OUT.append("")
OUT.append("→ 落卡 **[[R-HY-030-父母出资购房分割]]**。凡 2025-02-01 后受理的婚后父母出资购房分割争议，**不得再援引解释一第二十九条第二款**作「赠与双方」推定。")
OUT.append("")
OUT.append("### 4.2 夫妻间房屋给予不适用赠与合同任意撤销权")
OUT.append("")
OUT.append("《婚姻家庭编解释（二）》第五条第三款：夫妻间约定将一方房产给予另一方或共有、**未办理过户**的，给予方在离婚诉讼中反悔的，法院应结合给予目的、婚姻关系存续时间、共同生活及孕育子女情况、离婚过错、对家庭贡献等**判决房屋归属并确定是否补偿**；**撤销后无须补偿的，不适用民法典第六百五十八条赠与任意撤销权规则**。")
OUT.append("")
OUT.append("→ 落卡 **[[R-HY-025-房屋给予未过户的分割与撤销]]**。")
OUT.append("")
OUT.append("## 五、交付校验结果")
OUT.append("")
OUT.append("| 项 | 结果 |")
OUT.append("|---|---|")
OUT.append("| E0 卡片数 | 52 = 52 ✅ |")
OUT.append("| E1 rule_id 唯一 | 0 重复 ✅ |")
OUT.append("| E2 YAML 可解析 | 52/52 ✅（pyyaml 未降级） |")
OUT.append("| E3 必填字段 | 全备 ✅ |")
OUT.append("| E4 card_type | 52 = 审判要件卡 ✅ |")
OUT.append("| E5 rule_id = 文件名 | 52/52 ✅ |")
OUT.append("| E6 elements 非空 | 52/52 ✅ |")
OUT.append("| E7 support & reject 双非空 | 52/52 ✅ |")
OUT.append("| E8 八段齐全 | 52/52 ✅ |")
OUT.append("| E9 法条块来源+效力+无占位 | %d 块全通过 ✅ |" % TOTAL_LAW)
OUT.append("| E10 R2 声明 | 52/52 ✅ |")
OUT.append("| W1 页码双标注 | 0 告警 ✅ |")
OUT.append("| W2 review_date | 0 告警 ✅ |")
OUT.append("| W3/W4 死链 | 0 告警 ✅ |")
OUT.append("")
OUT.append("**合计：ERROR 0 / WARN 0。**")
OUT.append("")
OUT.append("## 六、关联")
OUT.append("")
OUT.append("- [[审判要件卡-卡型定义与总索引]]（03-连接 总索引，本批新增 §4.9）")
OUT.append("- [[审判要件卡-卡组可用性登记-婚姻家庭-2026-09-07]]（05-调用）")
OUT.append("- [[审判要件卡-拆卡排期表-2026-09]]")
OUT.append("")

p1 = os.path.join(ROOT, "02-提炼/审判要件卡/审判要件卡-入库索引-婚姻家庭-2026-09-07.md")
io.open(p1, 'w', encoding='utf-8').write("\n".join(OUT))
print("[写入] %s (%d chars)" % (p1, len("\n".join(OUT))))

# ---------------- 05-调用 可用性登记 ----------------
O2 = []
O2.append("---")
O2.append("type: 审判要件卡·卡组可用性登记")
O2.append("date: %s" % TODAY)
O2.append("program_type: 民事（婚姻家庭 / 离婚 / 婚约财产 / 扶养赡养 / 人身安全保护令）")
O2.append("scope: 知识飞轮/06-沉淀/裁判规则库/婚姻家庭")
O2.append("status: 已入库待调用（未实战）")
O2.append("groups:")
O2.append("  - R-HY-004~055（婚姻家庭纠纷 · 52 张）")
O2.append("consumer: 模拟法庭 judge_reviewer（法官心智）｜配置载体：小强律师数字分身系统/07-系统搭建与Skill配置/法律类skill 配置迭代-九阳神功/AI模拟法庭法官skill 配置说明书.md（23761 bytes，2026-09-07 实地 ls 确认存在）＋ 知识飞轮系统/03-连接/概念页/AI模拟法庭法官skill 配置说明书.md（5125 bytes，同日确认存在）")
O2.append("source: 《贵州法院类案审判要件指南（第二卷）》第五部分（PDF页254-306 / 书页222-275）")
O2.append("created: %sT09:50" % TODAY)
O2.append("updated: %sT09:50" % TODAY)
O2.append("tags:")
O2.append("  - 审判要件卡")
O2.append("  - 卡组登记")
O2.append("  - 婚姻家庭")
O2.append("  - 法官心智")
O2.append("  - 模拟法庭")
O2.append("---")
O2.append("")
O2.append("# 审判要件卡 · 卡组可用性登记（第七批 · 婚姻家庭纠纷 52 张）")
O2.append("")
O2.append("> **状态**：已通过交付校验（**ERROR 0 / WARN 0**），**可供调用，尚未实战**。")
O2.append("> **调用方式**：模拟法庭 `judge_reviewer` 在实质审查阶段按「四步推理链」消费（定位环节 → 逐项涵摄 → 举证校验 → 裁判预判 + 但书提醒）。")
O2.append("> **🔴 配置载体订正（2026-09-07 实地核验）**：上一批登记曾写「`小强律师数字分身系统/07-系统搭建与Skill配置/…/AI模拟法庭法官skill 配置说明书.md` 不存在」。本日 `find` / `ls -l` 实测该文件**真实存在**（23761 bytes，2026-09-06 09:56）。**两处载体均已挂载**，勿再按「不存在」处理。另 `agents/judge_reviewer/SOUL.md` 经全盘 `find` 确认**确不存在**，不写入口。")
O2.append("")
O2.append("## 一、卡组概览")
O2.append("")
O2.append("| 组 | 号段 | 张数 | 覆盖审理环节 | 典型用途 |")
O2.append("|---|---|---|---|---|")
for code, name, a, b, cov, use in GROUPS:
    rs = rows_for(a, b)
    O2.append("| %s | R-HY-%03d~%03d | %d | %s | %s |" % (code, a, b, len(rs), cov, use))
O2.append("")
O2.append("## 二、调用纪律（法官心智四步推理链）")
O2.append("")
O2.append("1. **定位审理环节** → 读 `review_step`")
O2.append("2. **逐项涵摄** → 用 `elements` 逐项比对本案事实")
O2.append("3. **举证校验** → 用 `burden_of_proof` 判断哪方未举证")
O2.append("4. **裁判预判 + 但书提醒** → 用 `ruling.support` / `ruling.reject` 给**候选结论**，同时触发 `negative_note`")
O2.append("")
O2.append("> **铁律 R2**：机器只给候选（`【候选·待人工确认】`），**不自动裁判**。")
O2.append("")
O2.append("## 三、⚠️ 调用前必读的六个要点")
O2.append("")
O2.append("1. **🔴 婚后父母出资购房已换版**（本批最高价值）：解释一第二十九条第二款「婚后父母出资无约即**推定赠与双方**」**已被解释二第八条取代**（法释〔2025〕1号，**2025-02-01 施行**），改为「**以出资来源及比例为基础 + 综合考量**」，**不再当然各半** → [[R-HY-030-父母出资购房分割]]。凡 2025-02-01 后受理案件**禁引旧推定**。")
O2.append("2. **夫妻间房屋给予不适用任意撤销权**：未过户的，按解释二第五条第三款判决归属与补偿，**不适用民法典第 658 条赠与任意撤销权** → [[R-HY-025-房屋给予未过户的分割与撤销]]。")
O2.append("3. **彩礼返还 ≠ 全退**：按共同生活时间长短、有无生育、彩礼数额与实际用途、双方过错、当地经济水平**酌定比例**；「闪婚闪离且未共同生活」才全额返还 → [[R-HY-020-彩礼返还比例裁量]]、[[R-HY-055-案例十闪婚闪离高额彩礼全额返还]]。生活困难须**从严认定**（无法维持当地基本生活水平，非相对下降）→ [[R-HY-021-生活困难从严认定]]。")
O2.append("4. **身份关系不能调解/不能自认**：婚姻效力、身份关系确认不适用调解与自认规则，调解优先但**不久调不决** → [[R-HY-004-审理四原则]]、[[R-HY-016-调解程序边界]]。")
O2.append("5. **共同债务「共签共认 + 家庭日常生活」双轨**：超出家庭日常生活需要的，债权人须举证用于共同生活/共同生产经营或基于共同意思表示 → [[R-HY-027-夫妻共同债务认定]]。")
O2.append("6. **地域效力**：本卡组系**贵州高院**裁判尺度统一指引，**非全国统一司法解释**；跨省援引须核当地口径（每卡 `geo_scope` 已标注）。")
O2.append("")
O2.append("## 四、可服务本所在办案件的判断（候选，非结论）")
O2.append("")
O2.append("| 在办事项 | 可命中卡片 | 说明 |")
O2.append("|---|---|---|")
O2.append("| 一般离婚/财产分割咨询 | A/B/D/E 组 | 覆盖管辖、准予离婚、财产定性与分割 |")
O2.append("| 彩礼返还争议 | C 组（R-HY-017~021） | 范围界定与比例裁量完整 |")
O2.append("| 家暴 / 保护令 | H 组（R-HY-046/047） | 主体扩张 + 执行与证据效力 |")
O2.append("| 老年当事人监护/赡养 | H 组（R-HY-042~045） | 与厚德基金会敬老业务可复用 |")
O2.append("")
O2.append("> **铁律 R2**：上表为**候选匹配**，实际办案须结合个案证据人工确认。")
O2.append("")
O2.append("## 五、未实战说明")
O2.append("")
O2.append("本卡组于 %s 入库，**尚未在模拟法庭或真实案件中调用**。首次调用后请回填本节：调用日期 / 案件 / 命中卡片 / 结论偏差 / 规则回流建议。" % TODAY)
O2.append("")
O2.append("## 六、关联")
O2.append("")
O2.append("- [[审判要件卡-入库索引-婚姻家庭-2026-09-07]]（02-提炼）")
O2.append("- [[审判要件卡-卡型定义与总索引]]（03-连接，§4.9）")
O2.append("")

p2 = os.path.join(ROOT, "05-调用/模拟法庭调用记录/审判要件卡-卡组可用性登记-婚姻家庭-2026-09-07.md")
if os.path.exists(p2):
    print("[跳过] 已存在：%s" % p2)
else:
    io.open(p2, 'w', encoding='utf-8').write("\n".join(O2))
    print("[写入] %s (%d chars)" % (p2, len("\n".join(O2))))
